# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_view', '0002_auto_20180206_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='heading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='velocity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='verticalAccuracy',
            field=models.IntegerField(default=0),
        ),
    ]
